import { MOVE_DIRECTIONS, MOVE_TYPES, MOVE_SQUARE_STATE } from "consts";

const KING_MOVE_DEFINITIONS = [
	[
		//type
		MOVE_TYPES.MOVE,
		//count
		1,
		//directions
		MOVE_DIRECTIONS.SIDEWAYS |
		MOVE_DIRECTIONS.FORWARD |
		MOVE_DIRECTIONS.BACKWARD |
		MOVE_DIRECTIONS.DIAGONAL,
		// squareState
		MOVE_SQUARE_STATE.EITHER,
		//canBeTaken
		false
	],
	[MOVE_TYPES.CASTLE]
];

export default KING_MOVE_DEFINITIONS;
